---
name: (( name_overrides.deployment_name ))

releases:
  - name: (( name_overrides.release_name ))
    version: (( release_version ))

compilation:
  workers: 3
  network: consats
  reuse_compilation_vms: true
  cloud_properties: (( iaas_settings.compilation_cloud_properties ))

update:
  canaries: 1
  canary_watch_time: 1000-180000
  update_watch_time: 1000-180000
  max_in_flight: 1
  serial: true

networks:
  - name: consats
    type: manual
    subnets: (( iaas_settings.subnet_configs.consats.subnets ))

resource_pools:
  - name: consats
    network: consats
    stemcell: (( iaas_settings.stemcell ))
    cloud_properties: (( iaas_settings.resource_pool_cloud_properties.consats.cloud_properties ))

jobs:
  - name: acceptance-tests
    lifecycle: errand
    networks:
      - name: consats
    templates:
      - name: acceptance-tests
        release: (( name_overrides.release_name ))
    instances: 1
    resource_pool: consats

properties:
  consul:
    acceptance_tests:
      bosh:
        target: (( iaas_settings.bosh.target ))
        username: (( iaas_settings.bosh.username ))
        password: (( iaas_settings.bosh.password ))
        director_ca_cert: (( iaas_settings.bosh.director_ca_cert || null ))
      aws:
        subnet: (( iaas_settings.aws.subnet || null ))
        access_key_id: (( iaas_settings.aws.access_key_id || null ))
        default_key_name: (( iaas_settings.aws.default_key_name || null ))
        default_security_groups: (( iaas_settings.aws.default_security_groups || [] ))
        region: (( iaas_settings.aws.region || null ))
        secret_access_key: (( iaas_settings.aws.secret_access_key || null ))
      registry:
        host: (( iaas_settings.registry.host ))
        username: (( iaas_settings.registry.username ))
        password: (( iaas_settings.registry.password ))
        port: (( iaas_settings.registry.port ))

# The keys below should not be included in the final stub
release_version: (( release_version_overrides || "latest" ))
iaas_settings: (( merge ))

name_defaults:
  release_name: consul
  deployment_name: consats
name_overrides:
  release_name: (( merge || name_defaults.release_name ))
  deployment_name: (( merge || name_defaults.deployment_name ))
