iaas_settings:
  bosh:
    target: https://192.168.50.4:25555
    username: admin
    password: admin
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  compilation_cloud_properties: {}
  resource_pool_cloud_properties:
    - name: consats
      cloud_properties: {}

  subnet_configs:
    - name: consats
      subnets:
      - cloud_properties:
          name: random
        range: 10.244.10.0/24
        reserved:
        - 10.244.10.1
        - 10.244.10.5
        - 10.244.10.9
        static: []
